venv: Support python venvs named .venv

diff --git a/.config/bash/rc.d/venv b/.config/bash/rc.d/venv
--- a/.config/bash/rc.d/venv
+++ b/.config/bash/rc.d/venv
@@ -1,10 +1,23 @@
 #!/bin/bash
 
+function mkvenv() {
+  python3 -m venv "${1:-venv}"
+}
+
 function activate() {
-  if [[ -d venv/ ]]; then
-    echo >&2 "Activating venv/ .."
-    source venv/bin/activate
+  local venv="${1:-venv}"
+  if [[ -d venv ]]; then
+    venv="venv"
+  elif [[ -d .venv ]]; then
+    venv=".venv"
+  fi
+  if [[ ! -d $venv ]]; then
+    echo >&2 "Requested venv ($venv) not present"
+  fi
+  echo >&2 -n "Activating $venv $(readlink -f $venv) .. "
+  if source $venv/bin/activate; then
+    echo >&2 "OK"
   else
-    echo >&2 "No venv detected"
+    echo >&2 "Failed: $?"
   fi
 }
