ssh-retry: Harden scripts to work under set -eu

diff --git a/.config/bin/ssh-retry b/.config/bin/ssh-retry
--- a/.config/bin/ssh-retry
+++ b/.config/bin/ssh-retry
@@ -1,6 +1,5 @@
 #!/bin/bash
 
-o 'Hello World'
 # ssh-retry
 # Keep trying to establish an ssh(1) connection to the target.
 # Give up and retry intelligently.
@@ -12,7 +11,7 @@ retry_floor="${min:-2}"               # Minimum time to wait before a retry if s
 retry_ceil="${max:-20}"               # Maximum time to wait before a retry if ssh was unsuccessful
 retry_interval="$retry_floor"         # How often to retry if ssh was unsuccessful
 retry_multiplier=1.15                 # Multiplier for backoff algorithm to ease traffic/load
-retry_preference="$retry_preference"  # Avoid the backoff algorithm altogether and use this constant time between retries
+# retry_preference="$retry_preference"  # Avoid the backoff algorithm altogether and use this constant time between retries
 quiet="${quiet:-0}"                   # no continuous logs, useful for invoking apps like top(1), etc.
 
 set -- -A -t -oConnectTimeout=5 "$@"
@@ -25,8 +24,8 @@ mkfifo "$stderr"
 
 exit_code=1
 while :; do
-  if (( $exit_code != 0 )); then
-    if [[ $retry_preference ]]; then
+  if (( exit_code != 0 )); then
+    if [[ ${retry_preference-} ]]; then
       retry_interval="$retry_preference"
     else
       retry_interval=$( perl -Wle '($c,$r,$m)=(@ARGV); print +(($r*$m) >= $c ? $c : $r*$m);' "$retry_ceil" "$retry_interval" "$retry_multiplier" )
@@ -38,12 +37,14 @@ while :; do
   (( quiet == 1 )) || \
     printf "%s  %s %s #%04.1f : " "$(date --rfc-3339=seconds | tr ' ' T)" "${0##*/}" "$*" "$retry_interval"
 
+  set +e
   ssh "$@" 2> >( tee "$stderr" )
   exit_code=$?
+  set -e
 
-  if (( $exit_code != 0 )); then
-    read errmsg < "$stderr";
-    if [[ $last_errmsg ]] && [[ $errmsg != $last_errmsg ]]; then
+  if (( exit_code != 0 )); then
+    read -r errmsg < "$stderr";
+    if [[ ${last_errmsg-} ]] && [[ $errmsg != "$last_errmsg" ]]; then
       # Something changed on the host and it's possibly becoming ready to accept connections
       # let's fall back to the floor and start the with smaller retry intervals
       retry_interval="$retry_floor"
