Redo ~/.fluxbox/keys
* Add ~/.googlize
* Document qterm
* Add mark-and-summon feature to fb.
* winctrl fixes include growto_{left,top}.

diff --git a/.bin/qterm b/.bin/qterm
--- a/.bin/qterm
+++ b/.bin/qterm
@@ -1,26 +1,109 @@
 #!/bin/bash
 
+# qterm(1)                          QTERM                               qterm(1)
+#
 # NAME
-#   qterm - launch a quick terminal (using a hotkey).
+#   qterm - lighweight {quick,quake} console.
+#
+# SYNOPSIS
+#   qterm
+#
+#   qterm [ toggle | show | hide | shade | raise |
+#           lower | fullscreen | max_horz | max_vert ]
+#
+# DESCTIPTION
+#   qterm uses the urxvt client (urxvtc) to spawn a terminal emulator hosting
+#   a console (i.e. a named ('qterm:') tmux session). The tmux session is 
+#   spawned if it does not exist otherwise it is attached to.
+#
+#   It is similar to other apps such as kuake(1), guake(1), tilda(1), etc
+#   but requires little in terms of additional packages (except those 
+#   listed in the DEPENDENCIES section below).
+#
+#   The terminal window is invoked if it is hidden or dismissed if it is 
+#   active by calling this script with no arguments effectively toggling
+#   the window. By mapping this script to a Window Manager's hotkey, one
+#   always 'the console' at hand and a very useful one at that.
+#
+#   Multiple parameters can be passed to this script and they will be executed
+#   in sequence. They are 
+#
+#     * show        -  Invoke qterm.
+#     * hide        -  Dismiss qterm.
+#     * toggle      -  Toggle visibility.
+#     * raise       -  Toggle placement on the topmost window layer.
+#     * lower       -  Toggle placement on the lowest window layer.
+#     * fullscreen  -  Toggle fullscreen.
+#     * max_horz    -  Toggle horizontal fullscreen.
+#     * max_vert    -  Toggle vertical fullscreen.
+#     * shade       -  Toggle whether or not the window is shaded.
+#     * help        -  Invoke the help menu.
 #
 # USAGE
-#   qterm [shade|skip_taskbar|raise|lower|hide|fullscreen]
+#   qterm   
+#     # same as 'qterm toggle' - toggle the visibility of the qterm window.
 #
-#   qterm   # toggles the display of the quickterm
-#           # this is mapped to a hotkey in the WM
+#   qterm raise show
+#     # show the qterm window after placing the qterm on the top window layer
+#     #   from here on. 'raise' is a toggle.
 #
+#   qterm fullscreen
+#     # Toggle the qterm window fullscreen from here on whether it is visible
+#     #   or not. 'fullscreen' is a toggle.
+#
+# DEPENDENCIES
+#   * rxvt-unicode-256color or rxvt-unicode
+#   * tmux
+#   * wmctrl
+#
+# REFERENCES
+#   * "Console (video game CLI) - Wikipedia"
+#     http://en.wikipedia.org/wiki/Quake-style_console
+#
+# AUTHOR
+#   Shalom Bhooshi
+#
+# COPYRIGHT
+#   Copyright © 2011 Shalom Bhooshi.  
+#   License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
+#   This is free software: you are free to change and redistribute it.
+#   There is NO WARRANTY, to the extent permitted by law.
+#
+# qterm(1)                         QTERM                                qterm(1)
 
-if [[ $1 = help ]]; then
+
+shopt -s nocaseglob nocasematch
+
+if [[ $1 = @(*help|-h) ]]; then
   cat <<EOH >&2
-    help
-    toggles: hide raised skip_taskbar
+  qterm [ toggle | show | hide | shade | raise | lower |
+          fullscreen | max_horz | max_vert ]
+
+     show        -  Invoke qterm.
+     hide        -  Dismiss qterm.
+     toggle      -  Toggle visibility.
+     raise       -  Toggle placement on the topmost window layer.
+     lower       -  Toggle placement on the lowest window layer.
+     shade       -  Toggle whether or not the window is shaded.
+     fullscreen  -  Toggle fullscreen.
+     max_horz    -  Toggle horizontal fullscreen.
+     max_vert    -  Toggle vertical fullscreen.
+     help        -  Show this message
+
 EOH
   exit 1;
 fi
 
+
 qtermWinID=$(printf "0x%x" "$(wmctrl -lx | awk '/qterm.URxvt/{print $1}')")
 
-if [[ $qtermWinID = 0x0 ]]; then
+wmctrl -i -r "$qtermWinID" -T qterm   # set its name
+
+if ! kill -0 $(pidof urxvtd) &>/dev/null; then 
+  urxvtd -q -o -f || { echo "Error launching urxvtd : $!"; exit 2; };
+fi
+
+if [[ $qtermWinID = 0x0 ]]; then # window is non-existent
   qtermSession="$(tmux ls | grep -Eio "^qterm:")"
   if [[ -z $qtermSession ]]; then
     urxvtc -name qterm -title qterm           \
@@ -36,54 +119,69 @@ fi
 
 currentWinID=$(printf "0x%x" "$(xprop -root _NET_ACTIVE_WINDOW | awk -F"# " '{print $2}')")
 
-wmctrl -i -r "$qtermWinID" -T qterm
-
 [[ $qtermWinID = $currentWinID ]] && isCurrentWindow=1
 
-# echo "$qtermWinID==$currentWinID isCurrentWindow: $isCurrentWindow" >&2
 
-if [[ $1 = skip_taskbar ]];
-then
-  wmctrl -i -r "$qtermWinID" -b toggle,skip_taskbar
-elif [[ $1 = raise ]];
-then
-  wmctrl -i -r "$qtermWinID" -b toggle,above
-  wmctrl -i -R "$qtermWinID"
-elif [[ $1 = lower ]];
-then
-  wmctrl -i -r "$qtermWinID" -b toggle,below
-elif [[ $1 = shade ]];
-then
-  wmctrl -i -r "$qtermWinID" -b toggle,shaded
-elif [[ $1 = hide ]];
-then
-  wmctrl -i -r "$qtermWinID" -b toggle,hidden
-elif [[ $1 = max_vert ]];
-then
-  wmctrl -i -r "$qtermWinID" -b toggle,maximized_vert
-elif [[ $1 = max_horz ]];
-then
-  wmctrl -i -r "$qtermWinID" -b toggle,maximized_horz
-elif [[ $1 = fullscreen ]];
-then
-  wmctrl -i -r "$qtermWinID" -b toggle,fullscreen
-elif [[ $isCurrentWindow = 1 ]];
-then
-  wmctrl -i -r "$qtermWinID" -b add,hidden
-else
-  wmctrl -i -r "$qtermWinID" -b remove,shaded
-  wmctrl -i -R "$qtermWinID"
-fi
+for op in "$@"; do
+  case "$op" in
 
+    toggle)
+      if [[ $isCurrentWindow = 1 ]]; then
+        exec "$0" hide
+      else
+        exec "$0" show
+      fi
+    ;;
 
-# while read -r key val; do 
-#   if [[ $key = _NET_WM_STATE\(ATOM\)* ]]; then
-#     [[ $val = *_NET_WM_STATE_HIDDEN* ]] && isHidden=1
-#   fi
-#   if [[ $key = _WIN_STATE\(CARDINAL\)* ]]; then
-#     [[ $val = *"= 2"* ]] && isMinimized=1
-#   fi
-# done < <(xprop -id "$qtermWinID")
-#echo "$qtermWinID==$currentWinID isCurrentWindow: $isCurrentWindow isHidden: $isHidden isMinimized: $isMinimized";
+    show)
+      wmctrl -i -r "$qtermWinID" -b remove,shaded
+      wmctrl -i -R "$qtermWinID"
+    ;;
 
+    hide)
+      wmctrl -i -r "$qtermWinID" -b add,hidden
+      wmctrl -i -r "$qtermWinID" -b add,skip_taskbar
+    ;;
 
+    skip_taskbar)
+      wmctrl -i -r "$qtermWinID" -b toggle,skip_taskbar
+    ;;
+
+    raise)
+      wmctrl -i -r "$qtermWinID" -b toggle,above
+    ;;
+
+    lower)
+      wmctrl -i -r "$qtermWinID" -b toggle,below
+    ;;
+
+    shade)
+      wmctrl -i -r "$qtermWinID" -b toggle,shaded
+    ;;
+
+    hide)
+      wmctrl -i -r "$qtermWinID" -b toggle,hidden
+    ;;
+
+    max_vert)
+      wmctrl -i -r "$qtermWinID" -b toggle,maximized_vert
+    ;;
+
+    max_horz)
+      wmctrl -i -r "$qtermWinID" -b toggle,maximized_horz
+    ;;
+
+    fullscreen)
+      wmctrl -i -r "$qtermWinID" -b toggle,fullscreen
+    ;;
+
+    *) # disregard parameter and default to emulating toggle.
+      if [[ $isCurrentWindow = 1 ]]; then
+        exec "$0" hide
+      else
+        exec "$0" show
+      fi
+    ;;
+
+  esac
+done
