Add changes for better interactive use   * Select running sessions   * Add new session from command line (or connect to existing one)

diff --git a/.bin/tmuxie b/.bin/tmuxie
--- a/.bin/tmuxie
+++ b/.bin/tmuxie
@@ -7,31 +7,56 @@ if ! type -P tmux &> /dev/null; then
   exit 2
 fi
 
-sessions=()
-while read -r session; do 
-  sessions+=( "$session" )
-done < <( tmux ls )
+function select_session_by_name() {
+  local sessions=()
+  local session_name;
 
-if (( ${#sessions[@]} == 0 )); then
-  printf 'No sessions, launch new one? [y/N] '; read n
-  if [[ -z $n || $n = [nN] ]]; then 
-    exit 1; 
+  while read -r session; do 
+    sessions+=( "$session" )
+  done < <( tmux ls 2> /dev/null )
+
+  if (( ${#sessions[@]} == 0 )); then
+    return 0
+  fi
+
+  perl -le 'for (@ARGV) { @_=split /\s+/; printf "%2s: %-12s %s\n", $c++, $_[0], (join " ", @_[1..$#_]) }' "${sessions[@]}" >&2
+  printf 'Which one? ' >&2; 
+  read reply
+
+  if [[ -z $reply ]]; then 
+    return 0;
+  elif [[ $reply = *[!0-9]* ]]; then
+    session_name="$reply";
+  elif ! (( reply < 0 && reply > ${#sessions[@]}-1 )); then
+    session_name="${sessions[reply]//:*/:}"
   else
-    exec tmux
+    echo "No such session. $reply" >&2
+    exit 2;
+  fi
+  
+  echo "$session_name"; return 0;
+}
+
+if (( $# >= 1 )); then
+  session_name="$1"
+elif test -t 0; then
+  session_name="$(select_session_by_name)"
+else
+  exit 1
+fi
+
+
+if [[ -n $session_name ]] && tmux ls 2>/dev/null | awk 'BEGIN{ec=1}$1 ~ /'"$session_name"'/{ec=0}END{exit ec}'; then
+  exec tmux attach -t "$session_name"
+elif [[ -n $session_name ]]; then
+  :
+elif test -t 0; then
+  printf 'Enter session name or RETURN to abort. ' >&2 ; read reply
+  if [[ -z $reply ]]; then 
+    exit 1;
+  else
+    session_name="$reply"
   fi
 fi
 
-for i in "${!sessions[@]}"; do
-  echo "$i. ${sessions[i]}"
-done
-printf 'Which one? '; read n
-
-set -vx
-if [[ -z $n ]]; then exit 1; fi
-
-if [[ $n = *[!0-9]* ]] || (( n < 0 || n > ${#sessions[@]}-1 )); then
-  echo "No such session. $n";
-  exit 2;
-fi
-
-exec tmux attach -t "${sessions[n]//:*/:}"
+exec tmux new-session -s "$session_name"
